=== crystal/autocode/generators/remotion/schema.json
{"$ref":"#/definitions/Spec","$schema":"http://json-schema.org/draft-07/schema#","definitions":{"AbsoluteFill":{"additionalProperties":false,"properties":{"style":{"additionalProperties":false,"properties":{"alignItems":{"type":"string"},"backgroundColor":{"type":"string"},"fontSize":{"type":"number"},"justifyContent":{"type":"string"}},"type":"object"}},"type":"object"},"Alignment":{"enum":["center","end","flex-end","flex-start","left","normal","right","space-around","space-between","space-evenly","start","stretch"],"type":"string"},"BaseElement":{"additionalProperties":false,"properties":{"action":{"type":"string"},"alt":{"type":"string"},"animate":{"$ref":"#/definitions/Style"},"auth":{"enum":["signedIn","signedOut"],"type":"string"},"class":{"$ref":"#/definitions/ClassExtended"},"collapsible":{"type":"boolean"},"component":{"type":"string"},"data":{"items":{},"type":"array"},"defaultChecked":{"type":"string"},"elements":{"$ref":"#/definitions/ElementArrayOrRef"},"for":{"type":"string"},"groups":{"items":{"additionalProperties":false,"properties":{"label":{"type":"string"},"menu":{"additionalProperties":false,"properties":{"items":{"items":{"additionalProperties":false,"properties":{"icon":{"type":"string"},"title":{"type":"string"},"url":{"type":"string"}},"type":"object"},"type":"array"}},"type":"object"}},"type":"object"},"type":"array"},"header":{"type":"string"},"href":{"type":"string"},"icon":{"type":"string"},"id":{"type":"string"},"initial":{"$ref":"#/definitions/Style"},"key":{"type":"string"},"model":{"type":"string"},"name":{"type":"string"},"onClick":{"additionalProperties":false,"properties":{"action":{"type":"string"},"data":{}},"required":["action"],"type":"object"},"placeholder":{"type":"string"},"props":{"$ref":"#/definitions/Record<string,(boolean|number|string|structure-904606755-1364-1394-904606755-1336-1394-904606755-1321-1395-904606755-1309-1396-904606755-637-1737-904606755-0-1790)>"},"required":{"type":"boolean"},"src":{"type":"string"},"style":{"$ref":"#/definitions/Style"},"tag":{"type":"string"},"target":{"type":"string"},"text":{"type":"string"},"transition":{"$ref":"#/definitions/Transition"},"type":{"type":"string"},"value":{"type":"string"},"whileHover":{"$ref":"#/definitions/StyleTransform"},"whileTap":{"$ref":"#/definitions/StyleTransform"}},"type":"object"},"BlendMode":{"enum":["normal","multiply","screen","overlay","darken","lighten","color-dodge","color-burn","hard-light","soft-light","difference","exclusion","hue","saturation","color","luminosity"],"type":"string"},"Class":{"type":"string"},"ClassExtended":{"anyOf":[{"$ref":"#/definitions/Class"},{"items":{"anyOf":[{"$ref":"#/definitions/Class"},{"additionalProperties":false,"properties":{"dark":{"anyOf":[{"$ref":"#/definitions/Class"},{"items":{"$ref":"#/definitions/Class"},"type":"array"}]}},"required":["dark"],"type":"object"},{"additionalProperties":false,"properties":{"hover":{"anyOf":[{"$ref":"#/definitions/Class"},{"items":{"$ref":"#/definitions/Class"},"type":"array"}]}},"required":["hover"],"type":"object"}]},"type":"array"}]},"Component":{"additionalProperties":false,"properties":{"elements":{"$ref":"#/definitions/ElementArrayOrRef"},"props":{"$ref":"#/definitions/Record<string,ComponentProp>"}},"type":"object"},"ComponentProp":{"additionalProperties":false,"properties":{"required":{"type":"boolean"},"type":{"$ref":"#/definitions/PrimitiveType"}},"type":"object"},"Composition":{"additionalProperties":false,"properties":{"absoluteFill":{"$ref":"#/definitions/AbsoluteFill"},"durationInFrames":{"type":"number"},"fps":{"type":"number"},"height":{"type":"number"},"id":{"type":"string"},"sequences":{"items":{"$ref":"#/definitions/Sequence"},"type":"array"},"width":{"type":"number"}},"type":"object"},"Display":{"enum":["block","contents","flex","flow-root","grid","inline-block","inline-flex","inline-grid","inline","list-item","none","table","table-row"],"type":"string"},"Element":{"anyOf":[{"$ref":"#/definitions/BaseElement"},{"$ref":"#/definitions/NativeElement"}]},"ElementArrayOrRef":{"anyOf":[{"items":{"$ref":"#/definitions/Element"},"type":"array"},{"$ref":"#/definitions/ElementIterator"},{"type":"string"}]},"ElementIterator":{"additionalProperties":false,"properties":{"class":{"type":"string"},"component":{"type":"string"},"data":{"items":{},"type":"array"},"elements":{"$ref":"#/definitions/ElementArrayOrRef"},"key":{"type":"string"},"model":{"type":"string"},"name":{"type":"string"},"tag":{"type":"string"}},"type":"object"},"NativeElement":{"additionalProperties":false,"properties":{"action":{"type":"string"},"alt":{"type":"string"},"animate":{"$ref":"#/definitions/Style"},"auth":{"enum":["signedIn","signedOut"],"type":"string"},"class":{"$ref":"#/definitions/ClassExtended"},"collapsible":{"type":"boolean"},"component":{"type":"string"},"data":{"items":{},"type":"array"},"defaultChecked":{"type":"string"},"elements":{"$ref":"#/definitions/ElementArrayOrRef"},"for":{"type":"string"},"groups":{"items":{"additionalProperties":false,"properties":{"label":{"type":"string"},"menu":{"additionalProperties":false,"properties":{"items":{"items":{"additionalProperties":false,"properties":{"icon":{"type":"string"},"title":{"type":"string"},"url":{"type":"string"}},"type":"object"},"type":"array"}},"type":"object"}},"type":"object"},"type":"array"},"header":{"type":"string"},"href":{"type":"string"},"icon":{"type":"string"},"id":{"type":"string"},"initial":{"$ref":"#/definitions/Style"},"key":{"type":"string"},"model":{"type":"string"},"name":{"type":"string"},"onClick":{"additionalProperties":false,"properties":{"action":{"type":"string"},"data":{}},"required":["action"],"type":"object"},"placeholder":{"type":"string"},"props":{"$ref":"#/definitions/Record<string,(boolean|number|string|structure-904606755-1364-1394-904606755-1336-1394-904606755-1321-1395-904606755-1309-1396-904606755-637-1737-904606755-0-1790)>"},"required":{"type":"boolean"},"src":{"type":"string"},"style":{"$ref":"#/definitions/Style"},"tag":{"enum":["a","div","h1","h2","h3","h4","h5","h6","iframe","img","input","li","section","span","ul"],"type":"string"},"target":{"type":"string"},"text":{"type":"string"},"transition":{"$ref":"#/definitions/Transition"},"type":{"type":"string"},"value":{"type":"string"},"whileHover":{"$ref":"#/definitions/StyleTransform"},"whileTap":{"$ref":"#/definitions/StyleTransform"}},"required":["tag"],"type":"object"},"ObjectFit":{"enum":["contain","cover","fill","none","scale-down"],"type":"string"},"Position":{"enum":["static","relative","absolute","fixed","sticky"],"type":"string"},"PrimitiveType":{"enum":["boolean","number","string"],"type":"string"},"Record<string,(boolean|number|string)>":{"additionalProperties":{"type":["boolean","number","string"]},"type":"object"},"Record<string,(boolean|number|string|structure-904606755-1364-1394-904606755-1336-1394-904606755-1321-1395-904606755-1309-1396-904606755-637-1737-904606755-0-1790)>":{"additionalProperties":{"anyOf":[{"type":"boolean"},{"type":"number"},{"type":"string"},{"additionalProperties":false,"properties":{"type":{"type":"string"}},"required":["type"],"type":"object"}]},"type":"object"},"Record<string,Component>":{"additionalProperties":{"$ref":"#/definitions/Component"},"type":"object"},"Record<string,ComponentProp>":{"additionalProperties":{"$ref":"#/definitions/ComponentProp"},"type":"object"},"Record<string,Composition>":{"additionalProperties":{"$ref":"#/definitions/Composition"},"type":"object"},"Sequence":{"additionalProperties":false,"properties":{"component":{"type":"string"},"durationInFrames":{"type":"number"},"from":{"type":"number"},"props":{"$ref":"#/definitions/Record<string,(boolean|number|string)>"},"text":{"type":"string"}},"type":"object"},"Spec":{"additionalProperties":false,"properties":{"components":{"$ref":"#/definitions/Record<string,Component>"},"compositions":{"$ref":"#/definitions/Record<string,Composition>"},"description":{"type":"string"},"name":{"type":"string"},"private":{"type":"boolean"},"title":{"type":"string"},"version":{"type":"string"}},"type":"object"},"Style":{"additionalProperties":false,"properties":{"alignItems":{"$ref":"#/definitions/Alignment"},"background":{"type":"string"},"backgroundAttachment":{"enum":["fixed","local","scroll"],"type":"string"},"backgroundBlendMod":{"$ref":"#/definitions/BlendMode"},"backgroundClip":{"enum":["border-box","padding-box","content-box","text"],"type":"string"},"backgroundColor":{"type":"string"},"backgroundImage":{"type":"string"},"borderRadius":{"type":"string"},"bottom":{"type":["number","string"]},"color":{"type":"string"},"display":{"$ref":"#/definitions/Display"},"fontFamily":{"type":"string"},"fontSize":{"type":"string"},"height":{"type":["number","string"]},"justifyContent":{"$ref":"#/definitions/Alignment"},"left":{"type":["number","string"]},"objectFit":{"$ref":"#/definitions/ObjectFit"},"opacity":{"type":"number"},"position":{"$ref":"#/definitions/Position"},"right":{"type":["number","string"]},"top":{"type":["number","string"]},"translateX":{"type":"number"},"translateY":{"type":"number"},"width":{"type":["number","string"]}},"type":"object"},"StyleTransform":{"additionalProperties":false,"properties":{"alignItems":{"$ref":"#/definitions/Alignment"},"background":{"type":"string"},"backgroundAttachment":{"enum":["fixed","local","scroll"],"type":"string"},"backgroundBlendMod":{"$ref":"#/definitions/BlendMode"},"backgroundClip":{"enum":["border-box","padding-box","content-box","text"],"type":"string"},"backgroundColor":{"type":"string"},"backgroundImage":{"type":"string"},"borderRadius":{"type":"string"},"bottom":{"type":["number","string"]},"color":{"type":"string"},"display":{"$ref":"#/definitions/Display"},"fontFamily":{"type":"string"},"fontSize":{"type":"string"},"height":{"type":["number","string"]},"justifyContent":{"$ref":"#/definitions/Alignment"},"left":{"type":["number","string"]},"objectFit":{"$ref":"#/definitions/ObjectFit"},"opacity":{"type":"number"},"position":{"$ref":"#/definitions/Position"},"right":{"type":["number","string"]},"rotate":{"type":"number"},"scale":{"type":"number"},"top":{"type":["number","string"]},"translateX":{"type":"number"},"translateY":{"type":"number"},"width":{"type":["number","string"]}},"type":"object"},"Transition":{"additionalProperties":false,"properties":{"delay":{"type":"number"},"duration":{"type":"number"}},"type":"object"}}}

=== crystal/autocode/packages/specui-cli/examples/remotion-example.json
{
  "name": "remotion-example",
  "version": "0.1.17",
  "private": true,
  "compositions": {
    "helloWorld": {
      "width": 1080,
      "durationInFrames": 160,
      "sequences": [
        {
          "durationInFrames": 81,
          "component": "bg",
          "props": {
            "video": "videos/planet.mp4"
          }
        },
        {
          "durationInFrames": 81,
          "from": 80,
          "component": "bg",
          "props": {
            "video": "videos/city.mp4"
          }
        },
        {
          "durationInFrames": 40,
          "component": "title",
          "props": {
            "color": "white",
            "text": "Hello"
          }
        },
        {
          "durationInFrames": 40,
          "from": 40,
          "component": "title",
          "props": {
            "color": "white",
            "text": "World"
          }
        },
        {
          "durationInFrames": 20,
          "from": 80,
          "component": "title",
          "props": {
            "color": "white",
            "text": "How"
          }
        },
        {
          "durationInFrames": 20,
          "from": 100,
          "component": "title",
          "props": {
            "color": "white",
            "text": "Are"
          }
        },
        {
          "durationInFrames": 20,
          "from": 120,
          "component": "title",
          "props": {
            "color": "white",
            "text": "You"
          }
        },
        {
          "durationInFrames": 20,
          "from": 140,
          "component": "title",
          "props": {
            "color": "white",
            "text": "Today?"
          }
        }
      ]
    }
  },
  "components": {
    "bg": {
      "props": {
        "video": {
          "required": true,
          "type": "string"
        }
      },
      "elements": [
        {
          "component": "video",
          "src": "$props.video",
          "style": {
            "height": 1080
          }
        }
      ]
    },
    "title": {
      "props": {
        "color": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "elements": [
        {
          "tag": "div",
          "style": {
            "alignItems": "center",
            "color": "$props.color",
            "display": "flex",
            "fontFamily": "Geist Mono",
            "fontSize": "16rem",
            "height": 1080,
            "justifyContent": "center",
            "position": "fixed",
            "width": 1080
          },
          "text": "$props.text"
        }
      ]
    }
  }
}
